/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShadowingRouteImport } from './routes/_authenticated/shadowing'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedFluencyRouteImport } from './routes/_authenticated/fluency'
import { Route as AuthenticatedFluencyJournalRouteImport } from './routes/_authenticated/fluency.journal'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShadowingRoute = AuthenticatedShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluencyRoute = AuthenticatedFluencyRouteImport.update({
  id: '/fluency',
  path: '/fluency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluencyJournalRoute =
  AuthenticatedFluencyJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedFluencyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fluency': typeof AuthenticatedFluencyRouteWithChildren
  '/generate': typeof AuthenticatedGenerateRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/shadowing': typeof AuthenticatedShadowingRoute
  '/fluency/journal': typeof AuthenticatedFluencyJournalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fluency': typeof AuthenticatedFluencyRouteWithChildren
  '/generate': typeof AuthenticatedGenerateRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/shadowing': typeof AuthenticatedShadowingRoute
  '/fluency/journal': typeof AuthenticatedFluencyJournalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/fluency': typeof AuthenticatedFluencyRouteWithChildren
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/shadowing': typeof AuthenticatedShadowingRoute
  '/_authenticated/fluency/journal': typeof AuthenticatedFluencyJournalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fluency'
    | '/generate'
    | '/history'
    | '/home'
    | '/library'
    | '/shadowing'
    | '/fluency/journal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fluency'
    | '/generate'
    | '/history'
    | '/home'
    | '/library'
    | '/shadowing'
    | '/fluency/journal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/fluency'
    | '/_authenticated/generate'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/library'
    | '/_authenticated/shadowing'
    | '/_authenticated/fluency/journal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shadowing': {
      id: '/_authenticated/shadowing'
      path: '/shadowing'
      fullPath: '/shadowing'
      preLoaderRoute: typeof AuthenticatedShadowingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluency': {
      id: '/_authenticated/fluency'
      path: '/fluency'
      fullPath: '/fluency'
      preLoaderRoute: typeof AuthenticatedFluencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluency/journal': {
      id: '/_authenticated/fluency/journal'
      path: '/journal'
      fullPath: '/fluency/journal'
      preLoaderRoute: typeof AuthenticatedFluencyJournalRouteImport
      parentRoute: typeof AuthenticatedFluencyRoute
    }
  }
}

interface AuthenticatedFluencyRouteChildren {
  AuthenticatedFluencyJournalRoute: typeof AuthenticatedFluencyJournalRoute
}

const AuthenticatedFluencyRouteChildren: AuthenticatedFluencyRouteChildren = {
  AuthenticatedFluencyJournalRoute: AuthenticatedFluencyJournalRoute,
}

const AuthenticatedFluencyRouteWithChildren =
  AuthenticatedFluencyRoute._addFileChildren(AuthenticatedFluencyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFluencyRoute: typeof AuthenticatedFluencyRouteWithChildren
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedShadowingRoute: typeof AuthenticatedShadowingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFluencyRoute: AuthenticatedFluencyRouteWithChildren,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedShadowingRoute: AuthenticatedShadowingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
